# Generated by Django 4.2.10 on 2025-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selexia_travel', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (англ)'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание (англ)'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='selexia_tra_user_id_04d151_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['excursion'], name='selexia_tra_excursi_96f109_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='selexia_tra_status_08ba36_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date'], name='selexia_tra_date_68bcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='selexia_tra_created_222d23_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='selexia_tra_slug_899af8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='selexia_tra_is_feat_d354f2_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='selexia_tra_slug_85c2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country'], name='selexia_tra_country_2279ee_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['slug'], name='selexia_tra_slug_ca8f35_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_popular'], name='selexia_tra_is_popu_1c56cf_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['slug'], name='selexia_tra_slug_cc2e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['price'], name='selexia_tra_price_73531c_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['city'], name='selexia_tra_city_id_2c8d65_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['status'], name='selexia_tra_status_5b489e_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['is_popular'], name='selexia_tra_is_popu_a89448_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['is_featured'], name='selexia_tra_is_feat_14b67b_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['rating'], name='selexia_tra_rating_fccf88_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['views_count'], name='selexia_tra_views_c_c9c2af_idx'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['created_at'], name='selexia_tra_created_2891d5_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='selexia_tra_user_id_d7e9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['item_type'], name='selexia_tra_item_ty_b692c7_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['excursion'], name='selexia_tra_excursi_0930fa_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['category'], name='selexia_tra_categor_8a7fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['country'], name='selexia_tra_country_8572e4_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['created_at'], name='selexia_tra_created_840733_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['excursion'], name='selexia_tra_excursi_b9e478_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='selexia_tra_user_id_5e5b80_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='selexia_tra_rating_705130_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved'], name='selexia_tra_is_appr_86512a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='selexia_tra_created_5f0266_idx'),
        ),
    ]
