# Generated by Django 4.2.10 on 2025-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selexia_travel', '0003_alter_excursion_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_popular'], name='selexia_tra_is_popu_cc8788_idx'),
        ),
    ]
