# Generated by Django 4.2.10 on 2025-08-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selexia_travel', '0004_city_is_popular_city_selexia_tra_is_popu_cc8788_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость экскурсии'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'excursion')},
        ),
    ]
