# Generated by Django 4.2.10 on 2025-08-22 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selexia_travel', '0005_alter_booking_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push уведомления')),
                ('profile_public', models.BooleanField(default=False, verbose_name='Публичный профиль')),
                ('show_reviews', models.BooleanField(default=True, verbose_name='Показывать отзывы')),
                ('preferred_language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=5, verbose_name='Предпочитаемый язык')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
